//
const ADD_WEBSITE  = "ADD_WEBSITE";
const SET_WEBSITES = "SET_WEBSITES";
const DELETE_WEBSITE = "DELETE_WEBSITE";

const ADD_WEBSITE_SUCCESS = "ADD_WEBSITE_SUCCESS";
const SET_WEBSITES_SUCCESS = "SET_WEBSITES_SUCCESS";
const DELETE_WEBSITE_SUCCESS = "DELETE_WEBSITE_SUCCESS";

//
const ADD_USER_AGENT = "ADD_USER_AGENT";
const SET_USER_AGENTS = "SET_USER_AGENTS";
const DELETE_USER_AGENT = "DELETE_USER_AGENT";

const ADD_USER_AGENT_SUCCESS = "ADD_USER_AGENT_SUCCESS";
const SET_USER_AGENTS_SUCCESS = "SET_USER_AGENTS_SUCCESS";
const DELETE_USER_AGENT_SUCCESS = "DELETE_USER_AGENT_SUCCESS";

//
const SWITCH_USER_AGENT = "SWITCH_USER_AGENT";
const SWITCH_USER_AGENT_SUCCESS = "SWITCH_USER_AGENT_SUCCESS";

export {
    //
    ADD_WEBSITE,
    SET_WEBSITES,
    DELETE_WEBSITE,

    ADD_WEBSITE_SUCCESS,
    SET_WEBSITES_SUCCESS,
    DELETE_WEBSITE_SUCCESS,

    //
    ADD_USER_AGENT,
    SET_USER_AGENTS,
    DELETE_USER_AGENT,

    ADD_USER_AGENT_SUCCESS,
    SET_USER_AGENTS_SUCCESS,
    DELETE_USER_AGENT_SUCCESS,

    //
    SWITCH_USER_AGENT,
    SWITCH_USER_AGENT_SUCCESS,
};
