const ADD_WEBSITE  = "ADD_WEBSITE";
const SET_WEBSITES = "SET_WEBSITES";
const SET_WEBSITES_SUCCESS = "SET_WEBSITES_SUCCESS";

export {
    ADD_WEBSITE,
    SET_WEBSITES,
    SET_WEBSITES_SUCCESS,
};
