const ADD_WEBSITE  = "ADD_WEBSITE";
const SET_WEBSITES = "SET_WEBSITES";

const ADD_WEBSITE_SUCCESS = "ADD_WEBSITE_SUCCESS";
const SET_WEBSITES_SUCCESS = "SET_WEBSITES_SUCCESS";

export {
    ADD_WEBSITE,
    SET_WEBSITES,

    ADD_WEBSITE_SUCCESS,
    SET_WEBSITES_SUCCESS,
};
